### ISSUE TITLE
nfs client-list not working

### ISSUE THREAD

**Issue by smnmtzgr** [dell/ansible-datadomain#4]
Trying to use the NFS modules.

- client-list doesn't work if set
- don't specify client-list (it is optional) doesn't work

get the following error when setting client-list to "10.0.0.5 10.0.0.6". E.g.
```
    - name: Create an export, optionally add clients
      dellemc.datadomain.nfs:
        state: create
        export-name: /data/col1/sap
        path: /data/col1/sap
        client-list: 10.0.0.5 10.0.0.6
        export-options: 'rw,no_root_squash,no_all_squash,secure'
```

The error:
```
fatal: [dd]: FAILED! => {"changed": false, "msg": {"changed": true, "failed": true, "invocation": {"module_args": {"client-list": "10.0.0.5 10.0.0.6", "export-name": "/data/col1/sap", "export-options": "rw,no_root_squash,no_all_squash,secure", "host": "dd", "new-export-name": null, "option-list": null, "password": null, "path": "/data/col1/sap", "port": 22, "private_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "state": "create", "username": "test", "version": null}}, "msg": "\n**** Failed to validate client list, duplicate client entry specified: 10.0.0.5\n\n"}}
```

I also get an error when not setting client-list (following the documentation it should be optional).
Can you please check whats going wrong here?
